package apperr

const (
	CodeAccountingNotFound         = "ACCOUNTING_NOT_FOUND"
	CodeAttachmentNotFound         = "ATTACHMENT_NOT_FOUND"
	CodeAuthRequired               = "AUTH_REQUIRED"
	CodeCannotDeleteHasAccounting  = "CANNOT_DELETE_HAS_ACCOUNTING"
	CodeCannotDeleteHasRoomsOrRent = "CANNOT_DELETE_HAS_ROOMS_OR_RENTS"
	CodeCurrentPasswordIncorrect   = "CURRENT_PASSWORD_INCORRECT"
	CodeEstateAccessDenied         = "ESTATE_ACCESS_DENIED"
	CodeEstateNotFound             = "ESTATE_NOT_FOUND"
	CodeForbidden                  = "FORBIDDEN"
	CodeGroupHasMembers            = "GROUP_HAS_MEMBERS"
	CodeGroupNameAlreadyExists     = "GROUP_NAME_ALREADY_EXISTS"
	CodeGroupNotFound              = "GROUP_NOT_FOUND"
	CodeInvalidCredentials         = "INVALID_CREDENTIALS"
	CodeRentAlreadyActive          = "RENT_ALREADY_ACTIVE"
	CodeRentAlreadyTerminated      = "RENT_ALREADY_TERMINATED"
	CodeRentNotFound               = "RENT_NOT_FOUND"
	CodeRentNotTerminated          = "RENT_NOT_TERMINATED"
	CodeRoomAlreadyRented          = "ROOM_ALREADY_RENTED"
	CodeRoomNotFound               = "ROOM_NOT_FOUND"
	CodeScheduleNotFound           = "SCHEDULE_NOT_FOUND"
	CodeTenantAlreadyLinked        = "TENANT_ALREADY_LINKED"
	CodeTenantHasActiveRents       = "TENANT_HAS_ACTIVE_RENTS"
	CodeTenantNotFound             = "TENANT_NOT_FOUND"
	CodeTokenExpired               = "TOKEN_EXPIRED"
	CodeUsernameAlreadyExists      = "USERNAME_ALREADY_EXISTS"
	CodeUserNotFound               = "USER_NOT_FOUND"
	CodeValidationError            = "VALIDATION_ERROR"
	CodeInternalError              = "INTERNAL_ERROR"
)
