server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://35.201.132.152:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
    - targets:
        - localhost
      labels:
        job: docker
        host: app_server
        __path__: /var/lib/docker/containers/*/*log

  - job_name: application
    static_configs:
    - targets:
        - localhost
      labels:
        job: application
        host: app_server
        service: api
        __path__: /var/log/app/*.log