server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://35.201.132.152:3100/loki/api/v1/push
    batchwait: 2s
    batchsize: 1048576
    backoff_config:
      min_period: 500ms
      max_period: 15s
      max_retries: 10
    timeout: 10s
    tenant_id: "app-server"

scrape_configs:
  # 監控所有容器的日誌
  - job_name: docker
    static_configs:
    - targets:
        - localhost
      labels:
        job: docker
        host: app_server
        __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            log: log
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - docker: {}  # 自動提取 Docker 標籤
      
  # 專門監控 API 服務的日誌
  - job_name: api_service
    static_configs:
    - targets:
        - localhost
      labels:
        job: api
        service: fastapi
        __path__: /var/lib/docker/containers/*api-service*/*-json.log  # 使用固定容器名稱
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            log: log
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2})\s(?P<level>[A-Z]+)?:?\s+(?P<message>.*)'
          source: log
      - labels:
          level:
      - regex:
          expression: '"(?P<method>GET|POST|PUT|DELETE|PATCH)\s+(?P<path>/[^\s"]*)\s+HTTP/[\d\.]+"\s+(?P<status>\d{3})'
          source: log
      - labels:
          method:
          path:
          status:
      - regex:
          expression: '(?P<error_type>error|exception|traceback)'
          source: log
      - labels:
          error_type:
          
  # 專門監控 MySQL 數據庫的日誌
  - job_name: mysql
    static_configs:
    - targets:
        - localhost
      labels:
        job: database
        service: mysql
        __path__: /var/lib/docker/containers/*db-service*/*-json.log  # 使用固定容器名稱
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            log: log
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - regex:
          expression: '(?P<log_type>(error|warning|note))'
          source: log
      - labels:
          log_type:
      
  # 專門監控 Redis 的日誌
  - job_name: redis
    static_configs:
    - targets:
        - localhost
      labels:
        job: database
        service: redis
        __path__: /var/lib/docker/containers/*redis-service*/*-json.log  # 使用固定容器名稱
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            log: log
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano