server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://35.201.132.152:3100/loki/api/v1/push
    batchwait: 2s
    batchsize: 1048576
    backoff_config:
      min_period: 500ms
      max_period: 15s
      max_retries: 10
    timeout: 10s
    tenant_id: "app-server"

scrape_configs:
  - job_name: docker
    static_configs:
    - targets:
        - localhost
      labels:
        job: docker
        host: app_server
        __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            log: log
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - regex:
          expression: '(?P<container_id>(?:[0-9a-f]{64}))\.log$'
          source: filename
      - labels:
          stream:
          container_id:

  - job_name: api_service
    static_configs:
    - targets:
        - localhost
      labels:
        job: api
        host: app_server
        service: fastapi
        __path__: /var/lib/docker/containers/*api*/*.log
    pipeline_stages:
      - json:
          expressions:
            log: log
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2})\s(?P<level>[A-Z]+)?:?\s+(?P<message>.*)'
          source: log
      - labels:
          level:
      - regex:
          expression: '"(?P<method>GET|POST|PUT|DELETE|PATCH)\s+(?P<path>/[^\s"]*)\s+HTTP/[\d\.]+"\s+(?P<status>\d{3})'
          source: log
      - labels:
          method:
          path:
          status:
      - regex:
          expression: '(?P<error_type>error|exception|traceback)'
          source: log
      - labels:
          error_type: